apiVersion: v1
kind: Service

metadata:
  name: pcode-three-service
  namespace: pcode
  labels:
    app: pcode-three

spec:
  selector:
    app: pcode-three
  type: NodePort
  clusterIP: 10.152.183.60
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30060
